// var BASE_CONFIG_URL = 'http://localhost:4000/';
// var BASE_CONFIG_URL = 'http://192.168.0.103:4000/';
var BASE_CONFIG_URL = 'http://freakified.github.io/PebbleChecklist/';
module.exports.BASE_CONFIG_URL = BASE_CONFIG_URL;

// Readable config templates with runtime minification
var CONFIG_CSS_TEMPLATE = [
  '* {',
  '  margin: 0;',
  '  padding: 0;',
  '  box-sizing: border-box;',
  '}',
  '',
  'body {',
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
  '  background-color: #EAEAEA;',
  '  color: #333333;',
  '  font-size: 17px;',
  '  line-height: 1.2;',
  '  -webkit-user-select: none;',
  '  user-select: none;',
  '}',
  '',
  '.header {',
  '  background-color: #FF4700;',
  '  color: white;',
  '  padding: 15px;',
  '  text-align: center;',
  '  font-size: 1.2em;',
  '  font-weight: 300;',
  '  position: fixed;',
  '  top: 0;',
  '  width: 100%;',
  '  z-index: 100;',
  '}',
  '',
  '.header::before {',
  '  content: \'‹\';',
  '  font-size: 40px;',
  '  position: absolute;',
  '  left: 16px;',
  '  top: -14px;',
  '  opacity: 0.6;',
  '  cursor: pointer;',
  '}',
  '',
  '.container {',
  '  padding: 60px 10px 20px;',
  '}',
  '',
  '.description {',
  '  padding: 10px;',
  '  font-size: 0.8em;',
  '  color: #666;',
  '  line-height: 1.4;',
  '}',
  '',
  '.items-section {',
  '  background-color: #F7F7F7;',
  '  border: 1px solid #DEDEDE;',
  '  margin: 15px 0;',
  '}',
  '',
  '.section-header {',
  '  padding: 3px 10px;',
  '  text-transform: uppercase;',
  '  font-size: 0.8em;',
  '  color: #A8A8A8;',
  '  border-bottom: 1px solid #DEDEDE;',
  '}',
  '',
  '.items-list {',
  '  min-height: 50px;',
  '}',
  '',
  '.item {',
  '  padding: 10px;',
  '  border-bottom: 1px solid #DEDEDE;',
  '  position: relative;',
  '  display: flex;',
  '  justify-content: space-between;',
  '  align-items: center;',
  '}',
  '',
  '.item:last-child {',
  '  border-bottom: none;',
  '}',
  '',
  '.delete-btn {',
  '  width: 30px;',
  '  height: 30px;',
  '  border-radius: 6px;',
  '  background: none;',
  '  border: none;',
  '  cursor: pointer;',
  '  position: relative;',
  '}',
  '',
  '.delete-btn::before, .delete-btn::after {',
  '  content: \'\';',
  '  position: absolute;',
  '  width: 24px;',
  '  height: 2px;',
  '  background-color: #A8A8A8;',
  '  border-radius: 2px;',
  '  top: 16px;',
  '}',
  '',
  '.delete-btn::before {',
  '  transform: rotate(45deg);',
  '  left: 3px;',
  '}',
  '',
  '.delete-btn::after {',
  '  transform: rotate(-45deg);',
  '  right: 3px;',
  '}',
  '',
  '.input-section {',
  '  margin: 15px 0;',
  '}',
  '',
  '.input-wrapper {',
  '  display: flex;',
  '  gap: 10px;',
  '}',
  '',
  '.item-input {',
  '  flex: 1;',
  '  padding: 10px;',
  '  border: 2px solid #DEDEDE;',
  '  border-radius: 5px;',
  '  font-size: 13px;',
  '  background-color: #F7F7F7;',
  '}',
  '',
  '.add-btn {',
  '  padding: 10px 20px;',
  '  background-color: #FF4700;',
  '  color: white;',
  '  border: none;',
  '  border-radius: 5px;',
  '  font-size: 0.8em;',
  '  cursor: pointer;',
  '}',
  '',
  '.submit-section {',
  '  text-align: center;',
  '  margin: 20px 0;',
  '}',
  '',
  '.submit-btn {',
  '  width: 95%;',
  '  height: 40px;',
  '  background-color: #FF4700;',
  '  color: white;',
  '  border: none;',
  '  border-radius: 5px;',
  '  font-size: 0.8em;',
  '  cursor: pointer;',
  '}',
  '',
  '.submit-btn.hidden {',
  '  display: none;',
  '}',
  '',
  '.add-item {',
  '  color: #FF4700;',
  '  padding: 10px;',
  '  text-align: center;',
  '  cursor: pointer;',
  '  border-top: 1px solid #DEDEDE;',
  '}',
  '',
  '.item input[type="checkbox"] {',
  '  margin-right: 10px;',
  '  transform: scale(1.2);',
  '}',
  '',
  '.item-label {',
  '  flex: 1;',
  '  cursor: pointer;',
  '  user-select: none;',
  '}'
].join('\n');
module.exports.CONFIG_CSS_TEMPLATE = CONFIG_CSS_TEMPLATE;

var CONFIG_BODY_TEMPLATE = [
  '<div class="header" onclick="cancelAndClose()">Checklist</div>',
  '<div class="container">',
  '  <div class="description">Manage your checklist items. You can edit existing items or add new ones.</div>',
  '  <div class="items-section">',
  '    <div class="section-header">Current Items</div>',
  '    <div class="items-list" id="current_items"></div>',
  '  </div>',
  '  <div class="items-section">',
  '    <div class="section-header">Add New Items</div>',
  '    <div class="items-list" id="items_to_add"></div>',
  '    <div class="add-item" onclick="showAddInput()">Add item</div>',
  '  </div>',
  '  <div class="submit-section">',
  '    <button id="submit_button" class="submit-btn hidden" onclick="submitData()">UPDATE WATCH</button>',
  '  </div>',
  '</div>'
].join('\n');
module.exports.CONFIG_BODY_TEMPLATE = CONFIG_BODY_TEMPLATE;

var CONFIG_SCRIPT_TEMPLATE = [
  '<script>',
  'let currentItems = [];',
  'let newItems = [];',
  '',
  'function getQueryParam(variable, defaultValue) {',
  '  const query = location.search.substring(1);',
  '  const vars = query.split("&");',
  '  for (let i = 0; i < vars.length; i++) {',
  '    const pair = vars[i].split("=");',
  '    if (pair[0] === variable) {',
  '      return decodeURIComponent(pair[1]);',
  '    }',
  '  }',
  '  return defaultValue || false;',
  '}',
  '',
  'function parseCurrentState() {',
  '  // Use embedded current state or fallback to URL parameter for backward compatibility',
  '  const currentState = window.CURRENT_STATE || getQueryParam("current_state", "[]");',
  '  try {',
  '    currentItems = JSON.parse(currentState);',
  '  } catch(e) {',
  '    console.log("Failed to parse current state:", e);',
  '    currentItems = [];',
  '  }',
  '}',
  '',
  'function renderCurrentItems() {',
  '  const container = document.getElementById("current_items");',
  '  container.innerHTML = "";',
  '  ',
  '  currentItems.forEach(function(item, index) {',
  '    const checkedAttr = item.c ? "checked" : "";',
  '    const itemHtml = \'<div class="item"><input type="checkbox" id="current_\' + index + \'" \' + checkedAttr + \' onchange="toggleCurrentItem(\' + index + \')"><label for="current_\' + index + \'" class="item-label">\' + escapeHtml(item.n) + \'</label><button class="delete-btn" onclick="deleteCurrentItem(\' + index + \')"></button></div>\';',
  '    container.insertAdjacentHTML("beforeend", itemHtml);',
  '  });',
  '}',
  '',
  'function toggleCurrentItem(index) {',
  '  currentItems[index].c = !currentItems[index].c;',
  '  updateSubmitButton();',
  '}',
  '',
  'function deleteCurrentItem(index) {',
  '  currentItems.splice(index, 1);',
  '  renderCurrentItems();',
  '  updateSubmitButton();',
  '}',
  '',
  'function cancelAndClose() {',
  '  const return_to = getQueryParam("return_to", "pebblejs://close");',
  '  document.location.href = return_to;',
  '}',
  '',
  'function showAddInput() {',
  '  const addDiv = document.querySelector(".add-item");',
  '  const inputHtml = \'<div class="input-section" id="input_section"><div class="input-wrapper"><input type="text" class="item-input" id="new_item_input" placeholder="Enter item..." autofocus><button class="add-btn" onclick="addItem()">Add</button></div></div>\';',
  '  addDiv.insertAdjacentHTML("beforebegin", inputHtml);',
  '  addDiv.style.display = "none";',
  '  ',
  '  const input = document.getElementById("new_item_input");',
  '  input.focus();',
  '  ',
  '  input.addEventListener("keypress", function(e) {',
  '    if (e.key === "Enter") {',
  '      addItem();',
  '    }',
  '  });',
  '  ',
  '  input.addEventListener("blur", function() {',
  '    setTimeout(function() {',
  '      if (input.value.trim() === "") {',
  '        hideAddInput();',
  '      }',
  '    }, 200);',
  '  });',
  '}',
  '',
  'function hideAddInput() {',
  '  const inputSection = document.getElementById("input_section");',
  '  if (inputSection) {',
  '    inputSection.remove();',
  '  }',
  '  const addDiv = document.querySelector(".add-item");',
  '  if (addDiv) {',
  '    addDiv.style.display = "block";',
  '  }',
  '}',
  '',
  'function addItem() {',
  '  const input = document.getElementById("new_item_input");',
  '  const text = input.value.trim();',
  '  ',
  '  if (text) {',
  '    newItems.push(text);',
  '    renderNewItems();',
  '    hideAddInput();',
  '    updateSubmitButton();',
  '  }',
  '}',
  '',
  'function deleteNewItem(index) {',
  '  newItems.splice(index, 1);',
  '  renderNewItems();',
  '  updateSubmitButton();',
  '}',
  '',
  'function renderNewItems() {',
  '  const container = document.getElementById("items_to_add");',
  '  container.innerHTML = "";',
  '  ',
  '  newItems.forEach(function(item, index) {',
  '    const itemHtml = \'<div class="item"><span>\' + escapeHtml(item) + \'</span><button class="delete-btn" onclick="deleteNewItem(\' + index + \')"></button></div>\';',
  '    container.insertAdjacentHTML("beforeend", itemHtml);',
  '  });',
  '}',
  '',
  'function escapeHtml(text) {',
  '  const div = document.createElement("div");',
  '  div.textContent = text;',
  '  return div.innerHTML;',
  '}',
  '',
  'function updateSubmitButton() {',
  '  const submitBtn = document.getElementById("submit_button");',
  '  const hasChanges = currentItems.length > 0 || newItems.length > 0;',
  '  ',
  '  if (hasChanges) {',
  '    const totalChanges = currentItems.length + newItems.length;',
  '    const buttonText = "UPDATE WATCH (" + totalChanges + " ITEM" + (totalChanges > 1 ? "S" : "") + ")";',
  '    submitBtn.textContent = buttonText;',
  '    submitBtn.classList.remove("hidden");',
  '  } else {',
  '    submitBtn.classList.add("hidden");',
  '  }',
  '}',
  '',
  'function submitData() {',
  '  const config = {',
  '    itemUpdates: []',
  '  };',
  '  ',
  '  // Add current items with their states',
  '  currentItems.forEach(function(item) {',
  '    config.itemUpdates.push({',
  '      name: item.n,',
  '      checked: item.c,',
  '      action: "update"',
  '    });',
  '  });',
  '  ',
  '  // Add new items',
  '  newItems.forEach(function(item) {',
  '    config.itemUpdates.push({',
  '      name: item,',
  '      checked: false,',
  '      action: "add"',
  '    });',
  '  });',
  '  ',
  '  const return_to = getQueryParam("return_to", "pebblejs://close#");',
  '  document.location.href = return_to + encodeURIComponent(JSON.stringify(config));',
  '}',
  '',
  '// Initialize the page',
  'parseCurrentState();',
  'renderCurrentItems();',
  'renderNewItems();',
  'updateSubmitButton();',
  '</script>'
].join('\n');
module.exports.CONFIG_SCRIPT_TEMPLATE = CONFIG_SCRIPT_TEMPLATE;

